// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://cuomozxsibsnzhydvque.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1b21venhzaWJzbnpoeWR2cXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODQzNTYsImV4cCI6MjA2MzY2MDM1Nn0.YA9jBPA3TvCLXe9QWJ0PObl75S8AaKFIeVV7g1Ad3l0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
	SUPABASE_URL,
	SUPABASE_PUBLISHABLE_KEY,
);
